filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

# filebeat.autodiscover:
#   providers:
#     - type: docker
#       hints.enabled: true
setup.kibana:
  host: "localhost:5601"
  username: elastic  
  password: changeme

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: [ "http://elasticsearch:9200" ]
  username: elastic
  password: changeme

filebeat.inputs:
- type: docker
  containers.ids: 
    - '*'
  